---
- name: Install cabal-install, happy and ghc
  package:
    name: cabal-install,happy,ghc
- name: Install stack
  package:
    name: stack
  when: ansible_os_family != 'RedHat' or ansible_distribution_major_version != '7'
